### ISSUE TITLE
Inconsistent prefix SMB or SBM?

### ISSUE THREAD

**Issue by LemADEC** [BuiltBrokenModding/SBM-Grappling#10]
As of 1.7.10-0.0.1b3, the mod is mixing the notation SBM and SMB. It's causing a bit of confusion when analyzing logs:
File name is SBM-GrapplingHook => ok
Mod id is smbgrapplinghook => nok
Entity id is smbEntityHook => nok
Item id is sbmGrapplingHook => ok
Unlocalized names are using smbgrapplinghook => nok

**Comment by DarkGuardsman** [comment]
Ah yes, bit of mistyping. Will fix later
