### ISSUE TITLE
Tooltip not translating

### ISSUE THREAD

**Issue by LemADEC** [BuiltBrokenModding/SBM-Grappling#5]
As of SBM-GrapplingHook-1.7.10-0.0.1b3-universal.jar on SSP and SMP, tooltip messages are not translating:
![image](https://cloud.githubusercontent.com/assets/4776032/26029681/e203e352-383b-11e7-8d6e-6cca1744c97e.png)

**Comment by DarkGuardsman** [comment]
Seems to be working in the dev workspace. You have the lang set to English right?

Also, translations are client side only so SMP has no effect on this kind of issue.

**Comment by LemADEC** [comment]
I'm in the default en_US.
I'm surprised to see the modid in the tooltip, with the "item." prefix, it might be looking assets in the "item.smbgrapplinghook" resource pack?

I guess I've seen too many SMP bugs on 1.10 with translation issues, lol

**Comment by DarkGuardsman** [comment]
I normally use the mod id to prevent overlap with translations as they are not stored per mod. That being said I just tested in dev and a live copy in multi-mc. I can not replicate the issue, try downloading the new version without other mods installed.

**Comment by LemADEC** [comment]
It seems to work now with SBM-GrapplingHook-1.7.10-0.1.0b20170514023901 :
![image](https://cloud.githubusercontent.com/assets/4776032/26032342/62f0ca98-3891-11e7-861e-f7e9c4e8b9bf.png)
