### ISSUE TITLE
Missing player offset?

### ISSUE THREAD

**Issue by LemADEC** [BuiltBrokenModding/SBM-Grappling#8]
As of SBM-GrapplingHook-1.7.10-0.0.1b3-universal.jar, hook appears to pull player from their chest, instead of their right hand. This is especially noticeable when going vertically up, as we are 'inside' the rope, instead of next to it.

**Comment by DarkGuardsman** [comment]
Intentional, there will be rendering to show a belt on the player as the hook is not required to stay suspended in air. This is designed to allow weapons and tools to be used with the hook.
